##Ansible Hosts File for Home Lab

[tftpservers]
tftp-server ansible_host=192.168.0.9

[ubuntu_desktop]
ubuntuPC ansible_host=192.168.0.10

[centos_server]
ansibletower ansible_host=192.168.0.8

[junos-siteA]
rsiteA-t2b01-vmx-junos ansible_host=10.0.0.1
rsiteA-t2b02-vmx-junos ansible_host=10.0.0.2

[junos-siteB]
rsiteB-t2b01-vmx-junos ansible_host=10.0.2.1
rsiteB-t2b02-vmx-junos ansible_host=10.0.2.2

[junos-siteC]
rsiteC-t2b01-vmx-junos ansible_host=10.0.1.1
rsiteC-t2b02-vmx-junos ansible_host=10.0.1.2

[vEOS-siteA]
rsiteA-dcc01-vEOS ansible_host=10.0.0.3
rsiteA-dcc02-vEOS ansible_host=10.0.0.4

[vEOS-siteB]
rsiteB-dcc01-vEOS ansible_host=10.0.2.3
rsiteB-dcc02-vEOS ansible_host=10.0.2.4

[vEOS-siteC]
rsiteC-dcc01-vEOS ansible_host=10.0.1.3
rsiteC-dcc02-vEOS ansible_host=10.0.1.4

[Arista_vEOS:children]
vEOS-siteA
vEOS-siteB
vEOS-siteC

[junos:children]
junos-siteA
junos-siteB
junos-siteC

[ubuntu:children]
tftpservers
ubuntu_desktop
